//! Reusable Search Skeletons for Combinatorial Backtracking.
//!
//! Directly corresponds to Marlow's higher-order search abstractions in Chapter 4:
//! - `search` in `timetable1.hs`: Pure sequential depth-first search.
//! - `parsearch` in `timetable2.hs`: Unbounded parallel divide-and-conquer (naive).
//! - `parsearch` in `timetable3.hs`: Depth-limited parallel search transitioning
//!   to sequential backtracking below a cutoff threshold.

use rayon::prelude::*;

/// Pure sequential depth-first search skeleton (`search` in `timetable1.hs`).
///
/// Explores the tree generated by `refine` until `is_finished` produces a solution.
pub fn seq_search<P, S, F, R>(state: P, is_finished: &F, refine: &R) -> Vec<S>
where
    F: Fn(&P) -> Option<S>,
    R: Fn(P) -> Vec<P>,
{
    if let Some(solution) = is_finished(&state) {
        return vec![solution];
    }

    refine(state)
        .into_iter()
        .flat_map(|child| seq_search(child, is_finished, refine))
        .collect()
}

/// Naive parallel search skeleton without depth cutoff (`parsearch` in `timetable2.hs`).
///
/// Forks child branches in parallel using Rayon at every node of the search tree.
/// Illustrates excessive task overhead on deep fine-grained trees.
pub fn par_search_naive<P, S, F, R>(state: P, is_finished: &F, refine: &R) -> Vec<S>
where
    P: Send + 'static,
    S: Send + 'static,
    F: Fn(&P) -> Option<S> + Sync,
    R: Fn(P) -> Vec<P> + Sync,
{
    if let Some(solution) = is_finished(&state) {
        return vec![solution];
    }

    let branches = refine(state);
    if branches.is_empty() {
        return Vec::new();
    }

    branches
        .into_par_iter()
        .flat_map(|child| par_search_naive(child, is_finished, refine))
        .collect()
}

/// Depth-limited parallel search skeleton (`parsearch` in `timetable3.hs`).
///
/// Evaluates branches in parallel across threads down to `max_depth`.
/// Once `depth >= max_depth`, execution shifts seamlessly to high-speed
/// sequential backtracking (`seq_search`) on the local worker thread.
pub fn par_search<P, S, F, R>(
    depth: usize,
    max_depth: usize,
    state: P,
    is_finished: &F,
    refine: &R,
) -> Vec<S>
where
    P: Send + 'static,
    S: Send + 'static,
    F: Fn(&P) -> Option<S> + Sync,
    R: Fn(P) -> Vec<P> + Sync,
{
    if let Some(solution) = is_finished(&state) {
        return vec![solution];
    }

    let branches = refine(state);
    if branches.is_empty() {
        return Vec::new();
    }

    if depth < max_depth {
        branches
            .into_par_iter()
            .flat_map(|child| par_search(depth + 1, max_depth, child, is_finished, refine))
            .collect()
    } else {
        branches
            .into_iter()
            .flat_map(|child| seq_search(child, is_finished, refine))
            .collect()
    }
}
